export { default as Header } from '@/components/Header.vue'
export { default as Feature } from '@/components/Feature.vue'
export { default as Price } from '@/components/Price.vue'
export { default as Testimoni } from '@/components/Testimoni.vue'
export { default as Navbar } from '@/components/Navbar.vue'
export { default as Footer } from '@/components/Footer.vue'
