export { default as ProductSection } from '@/views/home/ProductSection.vue'
export { default as FeturesSection } from '@/views/home/FeturesSection.vue'
export { default as Features2Section } from '@/views/home/Features2Section.vue'
export { default as PricingSection } from '@/views/home/PricingSection.vue'
export { default as CompanySection } from '@/views/home/CompanySection.vue'
